export const ADD_PRODUCT_SIZE = 'ADD_PRODUCT_SIZE';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const Update_PRODUCT_SIZE = 'Update_PRODUCT_SIZE';
export const DELETE_PRODUCT_SIZE = 'DELETE_PRODUCT_SIZE';
export const LIST_PRODUCTS = 'LIST_PRODUCTS';
export default ADD_PRODUCT | ADD_PRODUCT_SIZE | UPDATE_PRODUCT | DELETE_PRODUCT | Update_PRODUCT_SIZE | DELETE_PRODUCT_SIZE | LIST_PRODUCTS